imports:
  - { resource: tables.yml }

services:
    phpbb.cannedmessages.message.manager:
        class: phpbb\cannedmessages\message\manager
        arguments:
            - '@cache.driver'
            - '@phpbb.cannedmessages.nestedset'

    phpbb.cannedmessages.listener:
        class: phpbb\cannedmessages\event\main_listener
        arguments:
            - '@template'
            - '@auth'
            - '@phpbb.cannedmessages.message.manager'
            - '@language'
            - '@controller.helper'
        tags:
            - { name: event.listener }

    phpbb.cannedmessages.mcp.controller:
        class: phpbb\cannedmessages\controller\mcp_controller
        arguments:
            - '@user'
            - '@template'
            - '@language'
            - '@log'
            - '@request'
            - '@phpbb.cannedmessages.message.manager'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbb.cannedmessages.selected.controller:
        class: phpbb\cannedmessages\controller\selected_controller
        arguments:
            - '@phpbb.cannedmessages.message.manager'
            - '@request'

    phpbb.cannedmessages.nestedset:
        class: phpbb\cannedmessages\message\nestedset
        arguments:
            - '@dbal.conn'
            - '@phpbb.cannedmessages.table_lock'
            - '%phpbb.cannedmessages.tables.cannedmessages%'

    phpbb.cannedmessages.table_lock:
        class: phpbb\lock\db
        arguments:
            - cannedmessages.table_lock.cannedmessages_table
            - '@config'
            - '@dbal.conn'
